### ISSUE TITLE
Master branch fails to build 

### ISSUE THREAD

**Issue by jmguerreroh** [ros-controls/ros2_controllers#454]
**Describe the bug**
Does not compile

src/force_torque_sensor_broadcaster.cpp:56:18: error: ‘std::shared_ptr<rclcpp_lifecycle::LifecycleNode> controller_interface::ControllerInterfaceBase::node_’ is private within this context
   56 |   sensor_name_ = node_->get_parameter("sensor_name").as_string();

And much more...

**To Reproduce**
colcon build --symlink-install

**Expected behavior**
The package compiles and finishes correctly.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version galactic

**Additional context**
The master branch fails with the new package "admittance_controller"

**Comment by boilerbots** [comment]
admittance_controller missing dependency kinematics_interface which I can't find to resolve the build error.

**Comment by jmguerreroh** [comment]
> admittance_controller missing dependency kinematics_interface which I can't find to resolve the build error.

I solve it removing admittance_controller from source: https://github.com/jmguerreroh/ros2_controllers

**Comment by bmagyar** [comment]
* [X] Galactic is not supposed to work on 22.04.
* The master branch indeed won't compile unless you use the packages from the testing repos of ROS. It doesn't happen often but sometimes we have to merge things this way. This is the reason we have the `main` and `testing` variants of everything in the CI.

**Comment by bmagyar** [comment]
Also... Are you building from source on humble or on rolling? The master branches target rolling and may only work with the latest distro up to a point... There's a specific branch for humble.

**Comment by jmguerreroh** [comment]
> Also... Are you building from source on humble or on rolling? The master branches target rolling and may only work with the latest distro up to a point... There's a specific branch for humble.

I am building from humble. Where is the humble's branch for ros2_controllers? Documentation for humble (https://index.ros.org/p/ros2_controllers/#humble) indicates to use the master branch, and it does not work.
